### ISSUE TITLE
POST /api/chat/{roomId}/enter 참여자 첫 입장

### ISSUE THREAD

**Issue by JoonheeJeong** [FC-Chilli-Bubble/back-officener#109]
### 기능 설명
- 기존 참여자 모두에게 새로운 참여자 입장 메시지 송신 (messageType: ENTER)
- 기존 참여자들은 새로운 참여자의 정보를 받아야 함 (기존 채팅방 정보요청 참고)
  - 웹소켓으로 함께 송신
  - API 응답 테스트
- 채팅방 정보요청 시에는 ENTER 메시지에 대하여 시스템 메시지 기본 포맷 외 별도의 정보가 필요 없음
  - 어차피 멤버에 다 포함되어 반환됨

### To-do
- [x] api 설계
- [x] 해당 roomId가 존재하지 않는 경우 예외
- [x] 해당 roomId의 참여자가 아닌 경우 예외
- [x] 해당 roomId의 모든 참여자에게 웹소켓 ENTER 시스템 메시지 송신
  - 새로운 참여자 정보 포함
