### ISSUE TITLE
채팅방 연결 종료 (다른 화면으로 이동)

### ISSUE THREAD

**Issue by JoonheeJeong** [FC-Chilli-Bubble/back-officener#135]
### 핵심 조작 메소드
- `CustomTextWebSocketHandler#afterConnectionClosed`
---
### Todo
- [ ] ~해당 roomId의 함께배달이 존재하지 않는 경우 예외~
- [ ] ~해당 roomId의 함께배달이 종료된 경우 예외~
- [ ] ~해당 roomId의 함께배달에 참여하지 않는 경우 예외~
- [x] 해당 roomId의 유저 웹소켓세션 연결해제
